Repository stefanzweifel/laravel-sends, pull requests merged in 2022-01, with the labels that each got.

#6 Store Content of outgoing mail messages in the database
  README.md
  config/sends.php
  database/migrations/create_sends_table.php.stub
  src/Listeners/StoreOutgoingMailListener.php
  src/Models/Send.php
  tests/Listeners/StoreOutgoingMailListenerTest.php
  tests/TestSupport/resources/views/emails/test.blade.php
Labels: changelog:added

#7 Usage of custom model
  src/Support/HasSendsTrait.php
  src/Support/StoreMailables.php
Labels: changelog:fixed

#8 Add Support for Laravel 9 / Drop Support for Laravel 8
  .github/workflows/run-tests.yml
  composer.json
  src/Listeners/StoreOutgoingMailListener.php
  src/Support/StoreMailables.php
  tests/Listeners/AttachSendUuidListenerTest.php
  tests/Listeners/StoreOutgoingMailListenerTest.php
Labels: changelog:added, changelog:changed, changelog:removed
